### ISSUE TITLE
"Import failed, path does not exist or is not accessible" for items that do not exist

### ISSUE THREAD

**Issue by BzowK** [Radarr/Radarr#1541]
Good Morning - 

Thanks for all of your hard work!  I am wanting to completely migrate over from CP to Radarr so this past weekend bulk imported 3,000+ movies in my collection as the sync I set up with CP failed to import anything but the Wanted ones which took a while.  When having an issue afterwards, I was looking in the logs and found the below error:

Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\DownloadedMovieName

The issue is that not only does it appear 3-5 times a minute and address only 1 of 3 titles, no download has been attempted for any of them within SABnzbd any time recently, the titles do not appear in any of the Activity views, and the path it's pointing to doesn't exist _(the last folder of it doesn't)_

Is there a way to clear these out?  I am seeing that Radarr is using ~20% of my CPU a few times a minute and can't help to think this is related.

I'm using Radarr 0.2.0.696 which I freshly installed on Windows 10 x64 as a service.  I'm also using SABnzbd 	2.0.0 [55c4bef].  below is a snippet of the last few minutes from my log.  Please note that actual movie names have been changed to something generic.

Thanks!

17-5-17 10:00:30.7|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie2
17-5-17 10:00:36.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie1
17-5-17 10:00:39.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie3
17-5-17 10:00:44.2|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie4
17-5-17 10:01:29.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie2
17-5-17 10:01:34.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie1
17-5-17 10:01:38.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie3
17-5-17 10:01:42.7|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie4
17-5-17 10:02:30.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie2
17-5-17 10:02:36.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie1
17-5-17 10:02:40.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie3
17-5-17 10:02:45.4|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie4
17-5-17 10:03:15.8|Info|PreDBService|Starting PreDB Sync
17-5-17 10:03:32.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie2
17-5-17 10:03:38.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie1
17-5-17 10:03:41.3|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie3
17-5-17 10:03:46.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: D:\- App Cache -\sabNZBD\Complete\Radarr\Movie4

**Comment by fryfrog** [comment]
My guess is you're running Radarr as a service and haven't changed it from running as SYSTEM to running as yourself.

Also, can you put your log in \` \` back ticks so github doesn't swallow all the `\`?

**Comment by galli-leo** [comment]
See https://github.com/Radarr/Radarr/wiki/Common-Problems#why-cant-radarr-see-my-files-on-a-remote-server for more info

**Comment by Bothari** [comment]
I have this same issue, although on Ubuntu. It's nothing to do with remote server mappings, the directory in question is local and perfectly accessible (it is the only download directory I use, and it usually works). Radarr is trying to import 5 movies that I don't even recognise, which simply do not exist in my downloads directory.  Every 30 seconds it will attempt and fail the same thing. The activity queue is empty.

```
18-6-9 23:50:18.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /downloads/movies/What.We.Started.2018.720p.WEB-DL5.1.H264
18-6-9 23:50:18.2|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /downloads/movies/They.Remain.2018.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG
18-6-9 23:50:18.4|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /downloads/movies/They.Remain.2018.720p.AMZN.WEBRip.DDP5.1.x264-NTG-xpost
18-6-9 23:50:18.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /downloads/movies/The.Week.Of.2018.720p.NF.WEBRip.DD5.1.x264-NTb-xpost.1
18-6-9 23:50:18.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /downloads/movies/The.Week.Of.2018.720p.NF.WEBRip.DD5.1.x264-NTb-xpost

```

**Comment by dangitnew** [comment]
@fryfrog Had the same issue with Sonarr, disabled service and start Sonarr as regular app, issue is fixed. Thank you.

**Comment by fryfrog** [comment]
@Bothari: You're running in a docker and your paths are not the same between containers.

```

18-6-9 23:50:18.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /downloads/movies/What.We.Started.2018.720p.WEB-DL5.1.H264
```

**Comment by Bothari** [comment]
> @Bothari: You're running in a docker and your paths are not the same between containers.

@fryfrog If you'd read my complete post you'd see that I said "it usually works". My paths are fine.

```
    sabnzbd:
        image: "linuxserver/sabnzbd:latest"
        container_name: sabnzbd
        environment:
            - TZ = America/Los_Angeles
        ports:
            - 8905:8080
            - 9905:9090
        expose:
            - 8905
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/var/lib/htpc/sabnzbd:/config"
            - "/var/tmp/downloads/sabnzbd:/downloads/sabnzbd"
            - "/var/tmp/downloads/incomplete:/downloads/incomplete"
        restart: unless-stopped

    radarr:
        image: "linuxserver/radarr:latest"
        container_name: radarr
        environment:
            - TZ = America/Los_Angeles
        ports:
            - 8903:8903
        expose:
            - 8903
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/var/lib/htpc/radarr:/config"
            - "/var/tmp/downloads:/downloads"
            - "/nfs/lededje/Movies:/movies"
            - "/nfs/lededje/Scary:/scary"
        restart: unless-stopped
```
