### ISSUE TITLE
Import Cast, Crew and Collections from TMDB

### ISSUE THREAD

**Issue by scphantm** [Radarr/Radarr#3617]
**Is your feature request related to a problem? Please describe.**
This is tied to multiple features.  These features are designed to systematically add more detailed analysis capabilities to Radarr.

The feature chain is:

Related to 
#112
#367

**Describe the solution you'd like**
This feature is designed to simply begin importing and populating the data.  This is a small effort that can be completed with no changes to the UI, that way we can debate the best way to present and use the data.  

First, new tables will be created:

a proposed model would be: (reduce fields as necessary)

```
person:
  person_id: Long #Primary Key
  name: String # Indexed
  birthday: Date
  known_for_department: String
  deathday: Date # Nullable date
  also_known_as: [] # alternate names for the person
  gender: int # tmdb uses integers for gender, looks like 1 for female, 2 for male
  biography: String
  popularity: Decimal # should be a float to allow for computation
  place_of_birth: String
  profile_path: String
  adult: Boolean
  ImdbId: String
  homepage: String

person_credits:
  credit_id: string # Most likely primary key
  person_id: Long # soft link to person table
  TmdbId: integer # soft link back to movies table
  character: String
  release_date: string
  vote_count: integer
  video: boolean
  adult: boolean
  vote_average: integer or number
  title: string
  genre_ids: array[integer]
  original_language: string
  original_title: string
  popularity: number
  backdrop_path: string or null
  overview: string
  poster_path: string or null
  department: string # If the credit type is cast from tmdb, this will be "Acting"
  job: string # If the credit type is cast from tmdb, this will be "Cast"

collections:
  collection_id: integer # Primary key
  name: string
  overview: string
  poster_path: null
  backdrop_path: string
  Monitored: bool

collection_parts:
  collection_id: integer
  TmdbId: integer
  adult: boolean
  backdrop_path: null
  genre_ids: array[integer]
  original_language: string
  original_title: string
  overview: string
  release_date: string
  poster_path: string
  popularity: number
  title: string
  video: boolean
  vote_average: number
  vote_count: integer

```
The existing actor table will be delted

The people side is ment to build our our database on an as-needed basis, thats the reason why its a recurrsive call layout.  It will be slow to begin with, but as your datbase grows, it will become faster and faster for adds and refreshes because we already have the data.  Much of this will probably be simplified if we can use the sqlite json features (we can simply store the json objects) but im not sure how well that will work out.

```
def add_movie(movieid)
    movie = tmdb(/movie/{movie_id}, movieid)
    credits = tmdb(/movie/{movie_id}/credits, moviei)

    process_cast(credits)
    process_crew(credits)

    if movie.belongs_to_collection not null
        if not db.collections.exists(movie.belongs_to_collection.id)
            collection = tmdb(/collection/{collection_id}, movie.belongs_to_collection.id)

            if not db.collections.exists(collection.id)
                db.collections.Insert(collection)

                for each part in collection.parts
                    db.collection_parts.Insert(part)

    
def load_person(person_id)
    if not db.person.exists(person_id)
        person = tmdb(/person/{person_id}, person_id)
        db.person.Insert(person)

    person_credits = tmdb(/person/{person_id}/movie_credits, person_id)
    process_cast(person_credits)
    process_crew(person_credits)

def process_cast(credits)
    for each cast in credits.cast:
        cast.department = "Acting"
        cast.job = "Cast"
        db.person_credits.MaybeInsert(cast)
        load_person(cast.person_id)

def process_crew(credits)
    for each crew in credits.crew
        db.person_credits.MaybeInsert(crew)
        load_person(crew.person_id)
```

Seperate job functions will be created to update the person and collection information
