### ISSUE TITLE
Duplicates are continually being downloaded

### ISSUE THREAD

**Issue by henmunli** [Radarr/Radarr#3662]
**Describe the bug**
Movies are being repeatedly downloaded, often at lower quality.

This happened after I upgraded from the 0.2.x series to the 2.0.x series.

**To Reproduce**
1. Upgrade from 0.2.x series to 2.0.x series
2. Change no previous settings
3. Movies which had previously reached the Profile cut off are continually downloading new version

**Expected behavior**
When a film is tracked and the  Profile cut off has been reached new versions are no longer downloaded.

**Screenshots**
*History*
![](https://cl.ly/d645169d6997/Image%202019-08-02%20at%209.05.42%20am.png)

*Manual Search*
![](https://cl.ly/0f376eaa9f95/Image%2525202019-08-02%252520at%2525209.08.44%252520am.png)

*Files*
![](https://cl.ly/b821c70b7c32/Image%202019-08-02%20at%209.09.45%20am.png)

*Film Data*
![](https://cl.ly/b2b8f28ad74a/Image%202019-08-02%20at%209.09.14%20am.png)

*Profile*
![](https://cl.ly/814794698786/Image%202019-08-02%20at%209.18.26%20am.png)

**Desktop (please complete the following information):**
 - OS: Docker 18.03.1-ce, build 9ee9f40 on Ubuntu 16.04
 - Mono Version: 6.0.0.313
 - Version: 2.0.0.1413

**Debug Logs**
![debug logs](https://gist.github.com/henmunli/abd32b7676d2a679631d52ffde1634c8)

**More Info**
I noticed the Filesize for all affected films (and any others I check) is `0 B`.  Could that be related?

I'm running Radarr inside a Docker container on a Linux host with the files mounted from a Linux NAS via NFS.

On the Docker host the permissions are:
Film directory: `drwxrwsr-x 1024 users`
Film files: `-rw-rw-r-- 1 1024 users`

NAS permisssions:
Film directory: `drwxrwsr-x admin users`
Film files: `-rw-rw-r-- 1 admin users`

`users` has the GID 100 on both the Docker host and NAS.

I'm running the Radarr container with docker-compose and this config:
```
version: '3.6'

services:
  radarr:
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    image: linuxserver/radarr:2.0.0.1413-ls16
    ports:
      - "9003:7878"
    restart: unless-stopped
    volumes:
      - /home/henmunli/configs/radarr:/config
      - /mnt/downloads:/downloads
      - /mnt/media/Films:/movies
```

On the Docker host UID/GID 1000 is the primary user.

The 0B filesize indicator and line 142 of the gist (`UpgradeAllowedSpecification|File is no longer available, skipping this file.`) make me think this might be permissions related, however I can't find any specific log lines to back this up so it's definitely just a hunch.

Any help is much appreciated!
