### ISSUE TITLE
TimeOut for rootFolder post request

### ISSUE THREAD

**Issue by NicolasGuilloux** [Radarr/Radarr#4307]
**Describe the bug**
I created a docker-compose file where it builds the Radarr image (linuxserver/radarr:preview) and mount an NFS folder with read/write rights. I cannot import or download to this folder as the request to add it returns a 504 TimeOut.
I can browse it from the modal though so it is not a rights issue. I also can use it without trouble with Sonarr.

Moreover, I tweaked the Database to add manually the path and it seems to work well so I guess this is an issue with the API route `POST /api/v3/rootFolder`.

The only thing reported by the logs are the 2 following lines:
```
 -- Path: Invalid Path
 -- RootFolderPath: Invalid Path
```

**To Reproduce**
1. Build a docker-compose file to load the radarr image and mount a NFS Volume like the following one.
2. `docker-compose up -d`
3. Open the Debugger to watch the XHR requests.
4. Go to import and try to import the /nfs folder.
5. Wait for the rootFolder request failure.

**Attachments**

- docker-compose.yaml

```yaml
version: "3.7"

services:
    # Doc: https://hub.docker.com/r/linuxserver/radarr
    radarr:
        image: linuxserver/radarr:preview
        container_name: vault_radarr
        environment:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Paris
        ports:
            - 7878:7878
        restart: unless-stopped
        volumes:
            - ./Config/Radarr:/config
            - ./Downloads:/downloads
            - nfs-drive:/nfs

volumes:
    nfs-drive:
        driver: local
        driver_opts:
            type: "nfs"
            o: "addr=somewhere,rw"
            device: ":/your/path"
```

**Expected behavior**
It should add the folder in the RootFolder table and let us import the content

**Desktop (please complete the following information):**
 - *Host OS*: Arch Linux 
 - *Docker image*: linuxserver/radarr:preview
 - *Browser and Version*: Chromium Version 80.0.3987.163
 - *Version*: 3.0.0.2821
 - *Package Version*: 3.0.0.2821-ls4 by linuxserver.io
 - *.NET Core*: Yes
 - *Docker*: Yes
 - *DB Migration*: 171

**Debug Logs**As mentionned above, only 2 lines appeared when importing the folders:

```
 -- Path: Invalid Path
 -- RootFolderPath: Invalid Path
```
