### ISSUE TITLE
Radarr 3.0 core dumps on startup

### ISSUE THREAD

**Issue by ptarjan** [Radarr/Radarr#5531]
**Describe the bug**

The main docker (linuxserver/radarr) seems to have switched from 0.2 as the default to 3.0 about 2 weeks ago. When I pulled to update now, my container is stuck in a crashloop now.

**To Reproduce**
In my `docker-compose.yml`, this doens't work:
```
  radarr:
    container_name: radarr
    restart: always
    environment:
      - PUID=1006
      - PGID=1006
      - TZ=Americas/Los_Angeles
    volumes:
      - /home/radarr:/config
      - /mnt/data/Downloads:/downloads
      - /mnt/data/Movies:/movies
    ports:
      - 7878:7878
    image: linuxserver/radarr
```

You can see it core dumping like:
```
~ master $ docker-compose exec radarr /bin/bash
root@cdd508249ea5:/# /app/radarr/bin/Radarr
Aborted (core dumped)
```

But this does:
```
  radarr:
    container_name: radarr
    restart: always
    environment:
      - PUID=1006
      - PGID=1006
      - TZ=Americas/Los_Angeles
    volumes:
      - /home/radarr:/config
      - /mnt/data/Downloads:/downloads
      - /mnt/data/Movies:/movies
    ports:
      - 7878:7878
    image: linuxserver/radarr:version-v0.2.0.1504
```

**Expected behavior**
For it to work like 0.2 does

**Platform Information (please complete the following information):**
 - OS: Raspbery Pi
 - Docker: Yes
 - Mono or.NET Core Version: [e.g. Mono 5.8 or .Net Core 3.1.10] (found under System -> Status)
 - Browser and Version [e.g. chrome 86.0.4240.198] (Only needed for UI issues)
 - Radarr Version 3.0
 - Radarr Branch master

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
