### ISSUE TITLE
Remote path mapping and container volume settings in Docker

### ISSUE THREAD

**Issue by LoyerG** [Radarr/Radarr#5982]
Hello, 

Up until now I was using Radarr locally on my Synology, and I recently decided to relocate everything to Docker. 

I use transmission for my downloads, which will store the finished downloads in /volume1/downloads/complete. 

In the Docker-composite allowing the creation of my Radarr container, I have therefore set this path to "/downloads". But when I start Radarr, I get a message saying "You are using docker; download client Transmission places downloads in /downloads/complete but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings."(see attachment)
![radarr](https://user-images.githubusercontent.com/12394684/109473461-984ddf00-7a73-11eb-9ecb-eae59a7a2792.png)

I took a look at the doc I was referred to, but I confess I don't understand. Can someone help me? Thank you in advance.

Below the docker-composes of Radarr:

```
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /volume1/docker/Radarr/config:/config
      - /volume1/video/movie:/movies
      - /volume1/downloads/complete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
```

And here is the transmission's docker-compose: 

```
services
  transmission:
    image: linuxserver/transmission:latest
    network_mode: service:vpn
    depends_on:
      - vpn
    container_name: transmission
    environment:
      - PUID=1026
      - PGID=100
    volumes:
      - /volume1/docker/Transmission/config:/config
      - /volume1/downloads:/downloads
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
```
