### ISSUE TITLE
[BUG]: Cannot connect to trakt.tv list

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#6684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to add a list source for my radarr install. this is the error I got.

```
radarr           | [Warn] TraktListImport: Unable to connect to list 
radarr           | 
radarr           | [v3.2.2.5080] System.NullReferenceException: Object reference not set to an instance of an object.
radarr           |    at NzbDrone.Core.ImportLists.Trakt.List.TraktListRequestGenerator.GetMoviesRequest()+MoveNext() in D:\a\1\s\src\NzbDrone.Core\ImportLists\Trakt\List\TraktListRequestGenerator.cs:line 30
radarr           |    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
radarr           |    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
radarr           |    at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\ImportLists\HttpImportListBase.cs:line 187
radarr           | 
radarr           | 
radarr           | [Warn] RadarrErrorPipeline: Invalid request Validation failed: 
radarr           |  -- : Unable to connect to list, check the log for more details 
```

I am correctly authenticated with trakt, and i've tried different lists. None work

### Expected Behavior

Connect correctly to trakt.tv

### Steps To Reproduce

Here's the config I used on my docker-compose

```
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_network
      - traefik.http.routers.radarr.entrypoints=web,websecure
      - traefik.http.routers.radarr.rule=Host(`radarr.XXX.fr`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=leresolver
#      - traefik.http.routers.radarr.middlewares=radarr-auth
#      - traefik.http.middlewares.radarr-auth.basicauth.usersfile=/password/radarr/.htpasswd
      - com.centurylinklabs.watchtower.enable=true
    environment:
      TZ: Europe/Paris
      PUID: 1001 # set this to the UID of your user
      PGID: 1001 # set this to the GID of your user
    volumes:
      - /home/media/config/radarr:/config
      - /home/media/downloads/movies:/movies
      - /home/media/download/movies:/downloads
    networks:
      - traefik_network
```

Here's a screenshot of the radarr web ui

![Screenshot from 2021-10-28 11-23-01](https://user-images.githubusercontent.com/92302812/139227627-62842888-a548-4367-a64a-f8cb4653d240.png)

From what I've read on different CLOSED issues, it might be the auth callback that isn't getting the access and refresh tokens correctly

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr:3.2.2.5080-ls119 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Traefik
- Browser: Firefox
```

### What branch are you running?

Master

### Anything else?

.

[AB#1830](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1830)
