### ISSUE TITLE
Total Space, Free space is not shown the correct value if using logistc volume

### ISSUE THREAD

**Issue by dupeliuhao** [Radarr/Radarr#7308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using ubuntu 20.04 and docker version of radarr, mounting a logistic volume I created to /tv directory. The total size of this LV is around 9T. However, the total space radarr gets is actually 4.5 T, which seems to be the one of the disk space. This also caused the free space value shown in the UI not correct with seemly the free space on one of the disk.  I confirmed in Discord that this issue seems to be also happening if not using docker version of radarr. 

### Expected Behavior

The free space and total space showed on system info should be the total size of the logistic volume, not disk space.

### Steps To Reproduce

```
Docker compose file attached below:
---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/ttt/dockerish/radarr/config:/config
      - /home/ttt/mount/lv0/plex/movies:/movies #optional
      - /home/ttt/trsn-completed:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
```

The **lv0** under **/home/ttt/mount** directory is the mount point of this logistic volume.

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: 4.1.0.6175
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

The free space and total space value seem to be generated when first starting radarr. That's already gone because it's too old.

[AB#3190](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3190)
