### ISSUE TITLE
opening radarr in web browser throws error

### ISSUE THREAD

**Issue by ljmerza** [Radarr/Radarr#8088]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

im on chrome 109.0.5414.121 but this has been happening for a few months now. on firefox it works fine but on chrome it does before anything loads and i see a blank screen. my language is set to english. i tried running a completely new rdarr isntance to see if its some config on my end but its still happening

```
translate.js:33 Uncaught TypeError: Cannot read properties of null (reading 'MovieTitle')
    at Vo (translate.js:33:10)
    at 94619 (blocklistActions.js:36:14)
    at r (bootstrap:19:32)
    at startup:4:93
    at r.O (chunk loaded:25:12)
    at startup:5:43
    at index.js?h=LpIAZrRLe8uNDiTtqSyeqQ:1:1244834
```

### Expected Behavior

rdarr web works

### Steps To Reproduce

```
radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: unless-stopped
    network_mode: bridge
    env_file: ./env/global.env
    ports:
      - 7878:7878
    volumes:
      - ./volumes/radarr/config:/config
``` 

### Environment

```markdown
- OS: docker
- Radarr: cant see but latest docker version
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: chrome
- Database:
```

### What branch are you running?

Master

### Trace Logs?

cant grab them since radarr is completely broken

[AB#4895](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4895)
