### ISSUE TITLE
Import list exclusion edit missing on mobile

### ISSUE THREAD

**Issue by jt196** [Radarr/Radarr#9736]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Currently, on screens narrower than about 1000px, the year and spanner icon are missing from the import list exclusion list. They actually appear to be off screen rather than hidden, which makes me think this might not be intended behaviour. 

### Expected Behavior

Display the spanner on mobile devices. I'd have thought this was essential functionality for the list, the year less important. 

I'm not sure if this is intended behaviour or not... 

Solution would be to have a break for mobile devices. 

```html
<div class="ImportListExclusion-importExclusion-NU7R1">
    <div class="ImportListExclusion-tmdbId-H9u8c">597588</div>
    <div class="ImportListExclusion-movieTitle-TFFFF">Lucky Grandma</div>
    <div class="ImportListExclusion-movieYear-BWA8Y">2019</div>
    <div class="ImportListExclusion-actions-xNNGU"></div>
</div>
```
I had a little play with the CSS and this should work reasonably well, with titles disappearing behind the ellipsis if they exceed the space, year and spanner both visible:

```CSS
// allow the content to determine the size
.ImportListExclusion-movieYear-BWA8Y,
.ImportListExclusion-actions-xNNGU {
    flex: 0 0 auto;
}

// Give the tmdb id a set size
.ImportListExclusion-tmdbId-H9u8c {
    flex: 0 0 50px;
}

// stretch and grow according to size
.ImportListExclusion-movieTitle-TFFFF {
    min-width: 0;
    -max width: 100%; // remove this
    flex: 1 0 0%; 
}
```

At the moment in the browser it looks like multiple elements have flex-basis set to 700px etc. This should allow the movie title to grow or shrink depending on the screen size. Hope this helps. 

### Environment

```markdown
- OS: Mobile
- Radarr: 5.3.5.8570
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

1000px + - visible

![image](https://github.com/Radarr/Radarr/assets/8290163/0ca897b1-9a37-4974-909d-58290ee9ebb8)

~990px moving off screen

![image](https://github.com/Radarr/Radarr/assets/8290163/d1cc0a79-05ff-466b-be40-773b312425a7)

960px gone

![image](https://github.com/Radarr/Radarr/assets/8290163/e58f78d5-57c1-4f70-8d37-a22dd9038372)

915px year is moving off screen

![image](https://github.com/Radarr/Radarr/assets/8290163/51eeccff-1aaa-4c02-88ec-1ae53c676aca)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.
